@server = http://localhost:4004
@auth = 


### Read All Beers
# @name Beers_GET
GET {{server}}/devtoberfest/Beers
{{auth}}

### Read All Beers
# @name Beers_GET
GET {{server}}/devtoberfest/Beers/$count
{{auth}}


### Create New Beer
# @name Beers_POST
POST {{server}}/devtoberfest/Beers
Content-Type: application/json
{{auth}}

{
  "ID": "8489fdc3-63c8-4f23-b352-4c2d853a131b",
  "name": "Schwaben Bräu Meister Pils",
  "abv": "4.9",
  "ibu": 20,
  "brewery_ID": "6832ba00-c20e-48b4-a685-dca4aff2ca13",
  "style": "Pilsner - German",
  "about": "known for its crisp and refreshing taste, featuring a balanced blend of light malt and hop bitterness. It pours a light golden color with a medium-sized white head that dissipates quickly. The aroma is subtle, with hints of lemony hops and a fresh, grassy character"
}


### Read New Beer
# @name Beers_GET
GET {{server}}/devtoberfest/Beers(8489fdc3-63c8-4f23-b352-4c2d853a131b)
Content-Type: application/json
{{auth}}


### Update new beer
# @name Beers_PATCH
PATCH {{server}}/devtoberfest/Beers(8489fdc3-63c8-4f23-b352-4c2d853a131b)
Content-Type: application/json
{{auth}}

{
    "ibu": 10,
    "abv": "5.3",
    "style": "Lager - German"
}


### Delete new beer
# @name Beers_DELETE
DELETE {{server}}/devtoberfest/Beers(8489fdc3-63c8-4f23-b352-4c2d853a131b)
Content-Type: application/json
{{auth}}
